modLoader="javafml"
loaderVersion="[4,)"
license="MIT"

[[mods]]
modId="pingview"
version="${mod_version}"
displayName="${mod_name}"
logoFile="icon.png"
authors="${mod_authors}"
description='''${mod_description}'''

[[mixins]]
config="pingview.mixins.json"

[[dependencies.pingview]]
modId="neoforge"
type="required"
versionRange="[21.0.0,)"
ordering="NONE"
side="BOTH"

[[dependencies.pingview]]
modId="minecraft"
type="required"
versionRange="[1.21.6,)"
ordering="NONE"
side="BOTH"